### PR TITLE
[JENKINS-54166] Date parameter is lost upon restart

### PR DESCRIPTION
**Pull request by PierreBtz**
See https://issues.jenkins-ci.org/browse/JENKINS-54166 for details.

CC @reviewbybees

### CODE REVIEW

**Comment by leejaycoke** [comment]
@PierreBtz thanks. and Im sorry for late.
I will test this in 18hours. then will merge.

**Comment by aheritier** [comment]
Not so urgent @leejaycoke :-) Thanks a lot

**Comment by leejaycoke** [comment]
@aheritier Jenkins Core 1.614  >= J7.
Thanks.
merged.

**Comment by leejaycoke** [comment]
@aheritier Jenkins Core 1.614  >= J7.
Thanks.
merged.

**Comment by leejaycoke** [comment]
@aheritier Jenkins Core 1.614 >= J7 :)
@PierreBtz 
Github occurs many 500 status code errors.
I guess Github is in maintenance.
So I can't merge this.
I will try again in some hours later..

**Comment by PierreBtz** [comment]
@leejaycoke I think there were some issue with github this morning. Merge seems to have happen nonetheless. Any idea when you intend to do the next release (this is not urgent, just to have some idea)?

Thanks

**Comment by leejaycoke** [comment]
@PierreBtz yeah.. there were some issue.. git :<
finally release succeed (jenkins maven).
It will be showing in some hours..

**Comment by PierreBtz** [comment]
@leejaycoke great! Thanks a lot for the fast release!

**Pull request merged**
